import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { defineCommand } from "citty";
import { findDocoRoot } from "../find-root.js";
import { c, checkmark, cross, header, rule } from "../output.js";

/**
 * `doco install-hooks` — wire a pre-commit hook that runs `doco coverage`
 * and emits a warning when any modified file is not referenced in any
 * Action. Soft-fail by default — exit 0 to let the commit through; flip
 * --enforce to exit 1 and block.
 *
 * Per ADR-090.
 */
export const installHooksCmd = defineCommand({
  meta: {
    name: "install-hooks",
    description: "Install a git pre-commit hook that nudges on drift (ADR-090).",
  },
  args: {
    root: { type: "string", description: "Doco root (default: walk upward from cwd)." },
    enforce: {
      type: "boolean",
      description: "Block commits with uncovered files (exit 1). Default: warn-only.",
      default: false,
    },
  },
  async run({ args }) {
    const root = (args.root as string | undefined) ?? (await findDocoRoot());
    if (!root) {
      console.error(cross("Could not find doco.yaml."));
      process.exitCode = 2;
      return;
    }
    const gitDir = join(root, ".git");
    if (!existsSync(gitDir)) {
      console.error(cross(`No .git directory at ${root}. Run \`git init\` first.`));
      process.exitCode = 2;
      return;
    }
    const hooksDir = join(gitDir, "hooks");
    mkdirSync(hooksDir, { recursive: true });
    const hookPath = join(hooksDir, "pre-commit");

    const enforce = args.enforce as boolean;
    const body = renderHook(enforce);

    if (existsSync(hookPath)) {
      const existing = readFileSync(hookPath, "utf8");
      if (!existing.includes("DOCO_COVERAGE_HOOK_V1")) {
        console.error(
          cross(
            `A pre-commit hook already exists at ${hookPath} and isn't a Doco hook. Refusing to overwrite.`,
          ),
        );
        process.exitCode = 2;
        return;
      }
    }
    writeFileSync(hookPath, body, "utf8");
    chmodSync(hookPath, 0o755);

    console.log();
    console.log(header("Doco pre-commit hook installed"));
    console.log(rule());
    console.log(checkmark(`Hook:    ${c.dim(hookPath)}`));
    console.log(checkmark(`Mode:    ${enforce ? c.warn("enforce (blocks)") : c.dim("warn-only")}`));
    console.log(rule());
    console.log(c.dim("On every commit: runs `doco coverage`."));
    console.log(c.dim(enforce ? "Uncovered files → commit blocked." : "Uncovered files → printed; commit proceeds."));
    console.log();
  },
});

function renderHook(enforce: boolean): string {
  return `#!/bin/sh
# DOCO_COVERAGE_HOOK_V1 — pre-commit nudge for ADR-090 drift detection.
# Generated by \`doco install-hooks\`${enforce ? " --enforce" : ""}. Edit at your own risk.

if ! command -v doco >/dev/null 2>&1; then
  if command -v pnpm >/dev/null 2>&1; then
    DOCO_CMD="pnpm --silent --filter @doco/cli exec tsx src/index.ts"
  else
    echo "[doco hook] doco not on PATH; skipping coverage check"
    exit 0
  fi
else
  DOCO_CMD="doco"
fi

OUTPUT=$($DOCO_CMD coverage 2>&1)
STATUS=$?

if [ $STATUS -eq 0 ]; then
  exit 0
fi

echo "[doco coverage] drift detected:"
echo "$OUTPUT" | tail -20
${
  enforce
    ? `echo ""
echo "[doco coverage] blocking commit (enforce mode). Write an Action capturing this work, or re-run with --no-verify if intentional."
exit 1`
    : `echo ""
echo "[doco coverage] proceeding with commit (warn-only mode). Re-install with --enforce to block."
exit 0`
}
`;
}
