// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/e/:type": {
    params: {
      "type": string;
    };
  };
  "/e/:type/:id": {
    params: {
      "type": string;
      "id": string;
    };
  };
  "/search": {
    params: {};
  };
  "/lint": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/e/:type" | "/e/:type/:id" | "/search" | "/lint";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/e.$type._index.tsx": {
    id: "routes/e.$type._index";
    page: "/e/:type";
  };
  "routes/e.$type.$id.tsx": {
    id: "routes/e.$type.$id";
    page: "/e/:type/:id";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/lint.tsx": {
    id: "routes/lint";
    page: "/lint";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/e.$type._index": typeof import("./app/routes/e.$type._index.tsx");
  "routes/e.$type.$id": typeof import("./app/routes/e.$type.$id.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/lint": typeof import("./app/routes/lint.tsx");
};