// Generate src/schema-embedded.ts — a TS module that re-exports the
// contents of schema.sql as a plain string constant. Bundlers carry
// this string into whichever target they build (browser, SSR,
// serverless function) without needing a sibling file on disk. Solves
// "Could not locate schema.sql" in Vercel's serverless function
// packaging.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const schemaSql = readFileSync(join(root, "src/schema.sql"), "utf8");

const banner = "// AUTO-GENERATED by scripts/embed-schema.mjs — do not edit by hand.\n";
const schemaLiteral = JSON.stringify(schemaSql);

const out = `${banner}
export const SCHEMA_SQL: string =
  ${schemaLiteral};
`;

writeFileSync(join(root, "src/schema-embedded.ts"), out);
console.log(`embed-schema: wrote SCHEMA_SQL (${schemaSql.length} chars)`);
