// Generate src/schema-embedded.ts — a TS module that re-exports the
// contents of schema.sql and every migrations/*.sql as plain string
// constants. Bundlers carry these strings into whichever target they
// build (browser, SSR, serverless function) without needing a sibling
// file on disk. Solves "Could not locate schema.sql" in Vercel's
// serverless function packaging.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const schemaSql = readFileSync(join(root, "src/schema.sql"), "utf8");
const migrationsDir = join(root, "migrations");
const migrationFiles = readdirSync(migrationsDir)
  .filter((f) => /^\d{3,}_[a-z0-9_]+\.sql$/i.test(f))
  .sort();

const migrations = migrationFiles.map((name) => ({
  id: name.replace(/\.sql$/i, ""),
  sql: readFileSync(join(migrationsDir, name), "utf8"),
}));

const banner = "// AUTO-GENERATED by scripts/embed-schema.mjs — do not edit by hand.\n";
const schemaLiteral = JSON.stringify(schemaSql);
const migrationsLiteral = `[
${migrations
  .map(
    (migration) => `  {
    id: ${JSON.stringify(migration.id)},
    sql: ${JSON.stringify(migration.sql)},
  },`,
  )
  .join("\n")}
]`;

const out = `${banner}
export const SCHEMA_SQL: string =
  ${schemaLiteral};

export interface EmbeddedMigration {
  id: string;
  sql: string;
}

export const MIGRATIONS: EmbeddedMigration[] = ${migrationsLiteral};
`;

writeFileSync(join(root, "src/schema-embedded.ts"), out);
console.log(
  `embed-schema: wrote SCHEMA_SQL (${schemaSql.length} chars) and ${migrations.length} migrations`,
);
