// Plain-prose docs for agents who land on /onboarding/join/agent.
//
// Joining a Doco that already exists (because the repo carries
// doco.md and someone else minted an invite for you) is a single
// HTTP call.
export function loader() {
  const body = [
    "JOIN AN EXISTING DOCO — for agents",
    "",
    "Two situations bring you here:",
    "",
    "  (a) The user pasted you an invite URL (https://doco.to/invite/<code>)",
    "      and you need to redeem it.",
    "",
    "  (b) doco.md exists in the repo, .env doesn't have DOCO_KEY, and",
    "      you need to ask the user for an invite first.",
    "",
    "Case (a) — redeem an invite (no prior auth):",
    "",
    "    curl -fsS -X POST https://doco.to/api/v1/invites/<code>/redeem.json \\",
    "      -H 'Content-Type: application/json' \\",
    "      -d '{}'",
    "",
    "    Response (JSON):",
    "    {",
    "      \"doco_id\":              \"doco_01K…\",",
    "      \"doco_handle\":          \"<lowercase-kebab>\",",
    "      \"doco_url\":             \"https://doco.to/<doco_handle>/\",",
    "      \"doco_slug\":            \"<owner>/<slug>\",",
    "      \"doco_key\":             \"<64-hex>\",",
    "      \"next_steps_for_agent\": [ ...ordered checklist... ],",
    "      \"user_message_block\":   \"...verbatim prose to render...\"",
    "    }",
    "",
    "    Walk `next_steps_for_agent` top-to-bottom. The standard set is:",
    "      1. Write DOCO_KEY=<doco_key> into ./.env (create the file +",
    "         a basic .gitignore if either is missing).",
    "      2. If doco.md is missing, write it with the doco_url (so",
    "         future clones / CI / teammates' agents discover the Doco).",
    "      3. If AGENTS.md doesn't include `@./doco.md`, add the line.",
    "      4. If CLAUDE.md doesn't exist, write `@./AGENTS.md`.",
    "      5. Fetch the canonical: curl -fsS",
    "         https://doco.to/agent/${DOCO_KEY}/bootstrap.json",
    "      6. Render `user_message_block` to the user who pasted the",
    "         invite — verbatim, not paraphrased.",
    "",
    "Case (b) — ask the user for an invite:",
    "",
    "    \"I can see this repo is tracked at <doco_url>, but I don't",
    "     have an access key. Please get me an invite URL — either",
    "     (a) sign in at <doco_url>, click 'New invite', and paste the",
    "     URL back here, or (b) ask your already-connected agent to",
    "     POST /agent/<their-DOCO_KEY>/api/invites.json and paste the",
    "     resulting URL back here.\"",
    "",
    "    Wait for the paste. Don't loop. Don't try to authenticate any",
    "    other way.",
    "",
    "Full recipe with edge cases:",
    "  https://doco.to/onboarding/create/agent.txt (the create side)",
    "  https://doco.to/llms.txt (the entry point — both flows)",
    "",
    "If the invite has expired or was already consumed, the response",
    "is { status: 'expired' | 'consumed' | 'revoked' } with HTTP 410.",
    "Don't retry — ask the user for a fresh invite.",
  ].join("\n");
  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
