// Plain-prose docs for agents who land on /onboarding/join/agent.
//
// Joining a Doco that already exists starts from a single invite URL.
// The invite-specific route (/invite/<code>/agent.txt) carries the
// concrete code; this generic page explains the same flow when an agent
// arrives without one.
import { getPublicBaseUrl } from "@doco/shared";

export function loader({ request }: { request: Request }) {
  const baseUrl = getPublicBaseUrl(request).replace(/\/+$/, "");
  const body = [
    "JOIN AN EXISTING DOCO — for agents",
    "",
    "The normal handoff is just:",
    "",
    `  Let's collaborate with Doco on this project. Please redeem this invite URL: ${baseUrl}/invite/<code>`,
    "",
    "If you have the actual URL, prefer opening:",
    "",
    `  ${baseUrl}/invite/<code>/agent.txt`,
    "",
    "That invite-specific plain-text route includes the exact redeem URL.",
    "",
    "If you only have DOCO.md and no DOCO_ACCESS in ./.env, ask the user for",
    "an invite URL first:",
    "",
    '  "I can see this repo is tracked by Doco, but I need an invite URL.',
    '   Please open the Doco, mint a new invite, and paste the URL here."',
    "",
    "Once you have https://doco.to/invite/<code>, start with connector awareness:",
    "",
    "1. Check whether your runtime already exposes the Doco connector.",
    `   Look for native Doco tools, MCP tools, or an MCP server at ${baseUrl}/mcp.`,
    "",
    "2. If the connector is already installed, use it for the Doco work it supports.",
    "   If it can redeem invites, use it. If it cannot, make the API call below,",
    "   then use the connector for bootstrap/search/capture after DOCO_ACCESS is saved.",
    "",
    "3. If the connector is not installed, ask the project owner once whether they",
    "   want to install it for future sessions. If they decline or need to restart,",
    "   continue through the API in this session either way.",
    "",
    "Redeem an invite (no prior auth):",
    "",
    `    curl -fsS -X POST ${baseUrl}/api/v1/invites/<code>/redeem.json \\`,
    "      -H 'Content-Type: application/json' \\",
    "      -d '{}'",
    "",
    "    Response (JSON, abbreviated):",
    "    {",
    '      "doco_id":                "doco_01K…",',
    '      "doco_handle":            "<lowercase-kebab>",',
    '      "doco_url":               "https://doco.to/<doco_handle>/",',
    '      "doco_access":            "<64-hex>",',
    '      "canonical_instructions": "...protocol prose, the four invariants...",',
    '      "scopes":                 [...],',
    '      "constitution":           {...},',
    '      "onboarding_overlay":     null,',
    '      "next_steps_for_agent":   [ ...ordered checklist... ],',
    '      "user_message_block":     "...verbatim prose to render..."',
    "    }",
    "",
    "    Walk `next_steps_for_agent` top-to-bottom. The standard set is:",
    "      1. Write DOCO_ACCESS=<doco_access> into ./.env (create the file +",
    "         a basic .gitignore if either is missing).",
    "      2. If DOCO.md is missing, write it with the doco_url (so",
    "         future clones / CI / teammates' agents discover the Doco).",
    "      3. If AGENTS.md doesn't include `@./DOCO.md`, add the line.",
    "      4. If CLAUDE.md doesn't exist, write `@./AGENTS.md`.",
    "      5. Apply the protocol now. The `canonical_instructions` field",
    "         on this same response IS the protocol — do NOT make a",
    "         follow-on fetch to /api/v1/agent-bootstrap right now. The",
    "         fresh-token + second-fetch-returning-instructions pattern",
    "         trips agent-classifier credential-exfil heuristics. Later",
    "         sessions refresh via the helper or the agent-bootstrap",
    "         endpoint (different context, doesn't trip the heuristic).",
    "      6. Render `user_message_block` to the user who pasted the",
    "         invite — verbatim, not paraphrased.",
    "",
    "Full recipe with edge cases:",
    `  ${baseUrl}/onboarding/create/agent.txt (the create side)`,
    `  ${baseUrl}/llms.txt (the entry point — both flows)`,
    "",
    "If the invite has expired or was already consumed, the response",
    "is { status: 'expired' | 'consumed' | 'revoked' } with HTTP 410.",
    "Don't retry — ask the user for a fresh invite.",
  ].join("\n");
  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
