// Plain-prose docs for agents who land on /onboarding/join/agent.
//
// Joining a Doco that already exists (because the repo carries
// doco.md and someone else minted an invite for you) is a single
// HTTP call.
export function loader() {
  const body = [
    "JOIN AN EXISTING DOCO — for agents",
    "",
    "Two situations bring you here:",
    "",
    "  (a) The user pasted you an invite URL (https://doco.to/invite/<code>)",
    "      and you need to redeem it.",
    "",
    "  (b) doco.md exists in the repo, .env doesn't have DOCO_KEY, and",
    "      you need to ask the user for an invite first.",
    "",
    "Case (a) — redeem an invite (no prior auth):",
    "",
    "    curl -fsS -X POST https://doco.to/api/v1/invites/<code>/redeem.json \\",
    "      -H 'Content-Type: application/json' \\",
    "      -d '{}'",
    "",
    "    Response (JSON):",
    "    {",
    "      \"doco_id\":   \"doco_01K…\",",
    "      \"doco_url\":  \"https://doco.to/by-id/doco_01K…/\",",
    "      \"doco_slug\": \"<owner>/<slug>\",",
    "      \"doco_key\":  \"<64-hex>\"",
    "    }",
    "",
    "    Write DOCO_KEY=<doco_key> into ./.env (gitignored). The doco.md",
    "    in the repo already carries the URL — no need to write it again",
    "    unless doco.md is missing (in which case follow the create-side",
    "    recipe: write a doco.md with the URL).",
    "",
    "Case (b) — ask the user for an invite:",
    "",
    "    \"I can see this repo is tracked at <doco_url>, but I don't",
    "     have an access key. Please get me an invite URL — either",
    "     (a) sign in at <doco_url>, click 'New invite', and paste the",
    "     URL back here, or (b) ask your already-connected agent to",
    "     POST /agent/<their-DOCO_KEY>/api/invites.json and paste the",
    "     resulting URL back here.\"",
    "",
    "    Wait for the paste. Don't loop. Don't try to authenticate any",
    "    other way.",
    "",
    "Full recipe with edge cases:",
    "  https://doco.to/onboarding/create/agent.txt (the create side)",
    "  https://doco.to/llms.txt (the entry point — both flows)",
    "",
    "If the invite has expired or was already consumed, the response",
    "is { status: 'expired' | 'consumed' | 'revoked' } with HTTP 410.",
    "Don't retry — ask the user for a fresh invite.",
  ].join("\n");
  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
